### ISSUE TITLE
Stuck Lock

### ISSUE THREAD

**Issue by chrisspen** [ArsenyYankovsky/lucene-serverless#9]
Attempting a test of very slowly adding several thousand documents to the index, I'm seeing this error in the logs for the index function:

    ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread) Failed to run lambda: java.lang.RuntimeException: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /mnt/data/books/write.lock

Also there appears to be an indefinite build up of events in the write-queue, implying the lock file is never released, stopping the index function from further processing.

Do you know why this would be occurring of how to clear this lock file?

You have `reservedConcurrency: 1` in serverless.yml, so shouldn't there always be one instance of the index function running at any one time?

**Comment by chrisspen** [comment]
I think if any kind of error occurs, lambda crashes and the lock never gets cleared. I've added more error handling in my fork, as well as some cleanup logic for stale lock files, and this seems to have resolved the issue for me.

**Comment by ArsenyYankovsky** [comment]
@chrisspen Thanks for reporting it. Please submit a PR with your fixes.
